CREATE TABLE invoices (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    subject VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    tax_id INT UNSIGNED NOT NULL,
    currency_id INT UNSIGNED NOT NULL,
    customer_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB;